### ISSUE TITLE
My banner not loading

### ISSUE THREAD

**Issue by RezaMortazavi** [adform/adform-android-sdk#11]
I implemented adform adInLine.
the banner loads but its not my banner!
I checked the logs and i saw this error:

> onErrorLoading! A parser-blocking, cross site (i.e. different eTLD+1) script

I want to know what it is? and does it refer to my problem?

**Comment by RezaMortazavi** [comment]
anyone??

**Comment by andriusmisiunas** [comment]
Hi,

The error you see is due to document.write our scripts perform and loads resources from external sources. This warns that in case of slow connection, the external resources may be blocked from loading.

This should not however affect whether you see the ad or not - unless it is truly slow connection.

Please provide the master tag ID for our testing to make sure the ad is returned.
