### ISSUE TITLE
Disable refreshController.restart() if onErrorLoading

### ISSUE THREAD

**Issue by Secretbox1987** [adform/adform-android-sdk#13]
Hello. Please, help me to disable refreshController.restart() if onErrorLoading! A parser-blocking, cross site.
I use AdInlineLW into RecycleView.

**Comment by rprunskas** [comment]
Hi,

The error you see is due to document.write our scripts perform and loads resources from external sources. This warns that in case of slow connection, the external resources may be blocked from loading.

This should not however affect whether you see the ad or not - unless it is truly slow connection.
