### ISSUE TITLE
AdWebChromeClient error: parser-blocking

### ISSUE THREAD

**Issue by aparedes** [adform/adform-android-sdk#14]
The ad loads, but it doesn't present anything.

I get the following error:
`W/AdformSDK: AdWebView$AdWebChromeClient.onConsoleMessage():A parser-blocking, cross site (i.e. different eTLD+1) script`
`E/AdformSDK: onErrorLoading! A parser-blocking, cross site (i.e. different eTLD+1) script`

Is there a way to fix this?

**Comment by andriusmisiunas** [comment]
Hi,

The error you see is due to document.write our scripts perform and loads resources from external sources. This warns that in case of slow connection, the external resources may be blocked from loading.

This should not however affect whether you see the ad or not - unless it is truly slow connection.

Please provide the master tag ID for our testing to make sure the ad is returned.

**Comment by aparedes** [comment]
547667

**Comment by aparedes** [comment]
@andriusmisiunas now I'm getting "SERVER error. Error parsing entity. (TagData entity is empty)", can't find in your documentation what to do with this

**Comment by andriusmisiunas** [comment]
Hi,

This usually means that the ADX did not return any ads. Please check your targeting setup.

Andrius

**Comment by aparedes** [comment]
I also get `Application attempted to call on a destroyed WebView`

**Comment by rprunskas** [comment]
Please provide stacktrace so we can debug.
