### ISSUE TITLE
Banner not showing on API 28

### ISSUE THREAD

**Issue by valeriyatsoy** [adform/adform-android-sdk#25]
Works perfectly fine from api 19 to api 27.
But on api 28 there is a problem.
onAdLoadSuccess is called OK.
onAdVisibilityChange = true called OK.

However, banner is not showing. When debbuging inner webview I can see error in the Console: 
![image](https://user-images.githubusercontent.com/18663449/61708529-70aa7700-ad66-11e9-8d2a-beaeff1ac79b.png)

From Gradle file:
```
implementation 'com.adform.advertising.sdk:advertising-sdk:2.13.7@aar'
implementation 'com.google.android.gms:play-services-ads:7.8.0'
```

ID for this banner is 31567220

Please, help to debug. Thank you!

**Comment by rprunskas** [comment]
Hi,

The error you see is due to document.write our scripts perform and loads resources from external sources. This warns that in case of slow connection, the external resources may be blocked from loading.

This should not however affect whether you see the ad or not - unless it is truly slow connection.
